@startuml
'https://plantuml.com/class-diagram

title Diagrama de Clase de AlgoHoot
skinparam monochrome true
hide circle
skinparam classAttributeIconSize 0
class AlgoHoot{
    +comenzarPartida():void;
}
abstract class Limite{
    -preguntas:List<Pregunta>
    +Limite(List<Pregunta> preguntas)
    +Pregunta preguntaNoLimitada(List<Jugador> jugador)
    +Pregunta obtenerPreguntaSgte()
    +preguntasRestantesLimite():int
    +getPreguntas():List<Pregunta>;
}


class Lector{
    +generarPreguntas():ArrayList<Pregunta>
}
class Jugador{
    -nombre:String
    +Jugador(String nombre)
    +obtenerRespuesta():Respuesta
    +obtenerModificador():Modificacdor;
    +asignarPUntos():void
    +obtenerPuntaje():int

}
class Ronda{
    +Ronda(Pregunta pregunta, ArrayList<Jugador> jugadores);
    +jugarRonda():void
}


AlgoHoot .left.> Limite
AlgoHoot ..> Jugador
AlgoHoot .right.> Lector
AlgoHoot .up.> Ronda
@enduml